import React from 'react'
import Head from 'next/head'
// import Image from 'next/image'
import Script from 'next/script'
import Link from 'next/link'
import styles from '../../styles/Home.module.css'

const page = () => {

  return (
    
    <div>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      

      <nav className={styles.mainnav}>
        <ul>
          <Link href=''><li>Home</li></Link>
          <Link href='/about'><li>About</li></Link>
          <Link href='/blog'><li>Blog</li></Link>
          <Link href='/contact'><li>Contact</li></Link>
        </ul>
      </nav>

      <main className={styles.main}>
        <h1 className={styles.title}></h1>
      </main>


      <div className="blogs">
          <h2>Popular Blogs</h2>
          <div className="blogItem">
            <h3>How to learn JavaScript in 2022?</h3>
            <p>JavaScript is the language used to design logic for the web</p>
          </div>
          <div className="blogItem">
            <h3>How to learn JavaScript in 2022?</h3>
            <p>JavaScript is the language used to design logic for the web</p>
          </div>
          <div className="blogItem">
            <h3>How to learn JavaScript in 2022?</h3>
            <p>JavaScript is the language used to design logic for the web</p>
          </div>
        </div>
<Script src=' ' strategy='lazyOnload'>
</Script>

      <form>
        <input type="text" className='form-text' />
        <a href='pages/about'>about</a>
      </form>
    </div>
  )
}

export default page 